package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Administrativo generated by hbm2java
 */
public class Administrativo  implements java.io.Serializable {


     private AdministrativoId id;
     private InstitucionesEdu institucionesEdu;
     private Usuarios usuarios;
     private String admNombre;
     private String admLugarExpdoc;
     private String admSexo;
     private String admTelefono;
     private String admDireccion;
     private String admEmail;
     private Date admFecnac;
     private String admLugarnac;
     private String admEstadocivil;
     private String admCargo;

    public Administrativo() {
    }

    public Administrativo(AdministrativoId id, InstitucionesEdu institucionesEdu, Usuarios usuarios, String admNombre, String admLugarExpdoc, String admSexo, String admTelefono, String admDireccion, String admEmail, Date admFecnac, String admLugarnac, String admEstadocivil, String admCargo) {
       this.id = id;
       this.institucionesEdu = institucionesEdu;
       this.usuarios = usuarios;
       this.admNombre = admNombre;
       this.admLugarExpdoc = admLugarExpdoc;
       this.admSexo = admSexo;
       this.admTelefono = admTelefono;
       this.admDireccion = admDireccion;
       this.admEmail = admEmail;
       this.admFecnac = admFecnac;
       this.admLugarnac = admLugarnac;
       this.admEstadocivil = admEstadocivil;
       this.admCargo = admCargo;
    }
   
    public AdministrativoId getId() {
        return this.id;
    }
    
    public void setId(AdministrativoId id) {
        this.id = id;
    }
    public InstitucionesEdu getInstitucionesEdu() {
        return this.institucionesEdu;
    }
    
    public void setInstitucionesEdu(InstitucionesEdu institucionesEdu) {
        this.institucionesEdu = institucionesEdu;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getAdmNombre() {
        return this.admNombre;
    }
    
    public void setAdmNombre(String admNombre) {
        this.admNombre = admNombre;
    }
    public String getAdmLugarExpdoc() {
        return this.admLugarExpdoc;
    }
    
    public void setAdmLugarExpdoc(String admLugarExpdoc) {
        this.admLugarExpdoc = admLugarExpdoc;
    }
    public String getAdmSexo() {
        return this.admSexo;
    }
    
    public void setAdmSexo(String admSexo) {
        this.admSexo = admSexo;
    }
    public String getAdmTelefono() {
        return this.admTelefono;
    }
    
    public void setAdmTelefono(String admTelefono) {
        this.admTelefono = admTelefono;
    }
    public String getAdmDireccion() {
        return this.admDireccion;
    }
    
    public void setAdmDireccion(String admDireccion) {
        this.admDireccion = admDireccion;
    }
    public String getAdmEmail() {
        return this.admEmail;
    }
    
    public void setAdmEmail(String admEmail) {
        this.admEmail = admEmail;
    }
    public Date getAdmFecnac() {
        return this.admFecnac;
    }
    
    public void setAdmFecnac(Date admFecnac) {
        this.admFecnac = admFecnac;
    }
    public String getAdmLugarnac() {
        return this.admLugarnac;
    }
    
    public void setAdmLugarnac(String admLugarnac) {
        this.admLugarnac = admLugarnac;
    }
    public String getAdmEstadocivil() {
        return this.admEstadocivil;
    }
    
    public void setAdmEstadocivil(String admEstadocivil) {
        this.admEstadocivil = admEstadocivil;
    }
    public String getAdmCargo() {
        return this.admCargo;
    }
    
    public void setAdmCargo(String admCargo) {
        this.admCargo = admCargo;
    }




}


