package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1



/**
 * AdministrativoId generated by hbm2java
 */
public class AdministrativoId  implements java.io.Serializable {


     private String admCod;
     private int insDcodigo;
     private int munId;
     private int depId;
     private int secCodigo;

    public AdministrativoId() {
    }

    public AdministrativoId(String admCod, int insDcodigo, int munId, int depId, int secCodigo) {
       this.admCod = admCod;
       this.insDcodigo = insDcodigo;
       this.munId = munId;
       this.depId = depId;
       this.secCodigo = secCodigo;
    }
   
    public String getAdmCod() {
        return this.admCod;
    }
    
    public void setAdmCod(String admCod) {
        this.admCod = admCod;
    }
    public int getInsDcodigo() {
        return this.insDcodigo;
    }
    
    public void setInsDcodigo(int insDcodigo) {
        this.insDcodigo = insDcodigo;
    }
    public int getMunId() {
        return this.munId;
    }
    
    public void setMunId(int munId) {
        this.munId = munId;
    }
    public int getDepId() {
        return this.depId;
    }
    
    public void setDepId(int depId) {
        this.depId = depId;
    }
    public int getSecCodigo() {
        return this.secCodigo;
    }
    
    public void setSecCodigo(int secCodigo) {
        this.secCodigo = secCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdministrativoId) ) return false;
		 AdministrativoId castOther = ( AdministrativoId ) other; 
         
		 return ( (this.getAdmCod()==castOther.getAdmCod()) || ( this.getAdmCod()!=null && castOther.getAdmCod()!=null && this.getAdmCod().equals(castOther.getAdmCod()) ) )
 && (this.getInsDcodigo()==castOther.getInsDcodigo())
 && (this.getMunId()==castOther.getMunId())
 && (this.getDepId()==castOther.getDepId())
 && (this.getSecCodigo()==castOther.getSecCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAdmCod() == null ? 0 : this.getAdmCod().hashCode() );
         result = 37 * result + this.getInsDcodigo();
         result = 37 * result + this.getMunId();
         result = 37 * result + this.getDepId();
         result = 37 * result + this.getSecCodigo();
         return result;
   }   


}


