package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private AsignaturaId id;
     private Docente docente;
     private String asiNombre;
     private int asiIntesidad;
     private Set asistencias = new HashSet(0);
     private Set indicadoreses = new HashSet(0);
     private Set cursos = new HashSet(0);
     private Set notas = new HashSet(0);

    public Asignatura() {
    }

	
    public Asignatura(AsignaturaId id, Docente docente, String asiNombre, int asiIntesidad) {
        this.id = id;
        this.docente = docente;
        this.asiNombre = asiNombre;
        this.asiIntesidad = asiIntesidad;
    }
    public Asignatura(AsignaturaId id, Docente docente, String asiNombre, int asiIntesidad, Set asistencias, Set indicadoreses, Set cursos, Set notas) {
       this.id = id;
       this.docente = docente;
       this.asiNombre = asiNombre;
       this.asiIntesidad = asiIntesidad;
       this.asistencias = asistencias;
       this.indicadoreses = indicadoreses;
       this.cursos = cursos;
       this.notas = notas;
    }
   
    public AsignaturaId getId() {
        return this.id;
    }
    
    public void setId(AsignaturaId id) {
        this.id = id;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public String getAsiNombre() {
        return this.asiNombre;
    }
    
    public void setAsiNombre(String asiNombre) {
        this.asiNombre = asiNombre;
    }
    public int getAsiIntesidad() {
        return this.asiIntesidad;
    }
    
    public void setAsiIntesidad(int asiIntesidad) {
        this.asiIntesidad = asiIntesidad;
    }
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }
    public Set getIndicadoreses() {
        return this.indicadoreses;
    }
    
    public void setIndicadoreses(Set indicadoreses) {
        this.indicadoreses = indicadoreses;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }
    public Set getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set notas) {
        this.notas = notas;
    }




}


