package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia  implements java.io.Serializable {


     private AsistenciaId id;
     private Asignatura asignatura;
     private Docente docente;
     private Estudiante estudiante;
     private int asisAsistencia;
     private Date asisFecha;

    public Asistencia() {
    }

    public Asistencia(AsistenciaId id, Asignatura asignatura, Docente docente, Estudiante estudiante, int asisAsistencia, Date asisFecha) {
       this.id = id;
       this.asignatura = asignatura;
       this.docente = docente;
       this.estudiante = estudiante;
       this.asisAsistencia = asisAsistencia;
       this.asisFecha = asisFecha;
    }
   
    public AsistenciaId getId() {
        return this.id;
    }
    
    public void setId(AsistenciaId id) {
        this.id = id;
    }
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public int getAsisAsistencia() {
        return this.asisAsistencia;
    }
    
    public void setAsisAsistencia(int asisAsistencia) {
        this.asisAsistencia = asisAsistencia;
    }
    public Date getAsisFecha() {
        return this.asisFecha;
    }
    
    public void setAsisFecha(Date asisFecha) {
        this.asisFecha = asisFecha;
    }




}


