package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private CursoId id;
     private Docente docenteByImparteClases;
     private Docente docenteByDirige;
     private InstitucionesEdu institucionesEdu;
     private int curGrado;
     private Set asignaturas = new HashSet(0);
     private Set estudiantes = new HashSet(0);

    public Curso() {
    }

	
    public Curso(CursoId id, Docente docenteByImparteClases, Docente docenteByDirige, InstitucionesEdu institucionesEdu, int curGrado) {
        this.id = id;
        this.docenteByImparteClases = docenteByImparteClases;
        this.docenteByDirige = docenteByDirige;
        this.institucionesEdu = institucionesEdu;
        this.curGrado = curGrado;
    }
    public Curso(CursoId id, Docente docenteByImparteClases, Docente docenteByDirige, InstitucionesEdu institucionesEdu, int curGrado, Set asignaturas, Set estudiantes) {
       this.id = id;
       this.docenteByImparteClases = docenteByImparteClases;
       this.docenteByDirige = docenteByDirige;
       this.institucionesEdu = institucionesEdu;
       this.curGrado = curGrado;
       this.asignaturas = asignaturas;
       this.estudiantes = estudiantes;
    }
   
    public CursoId getId() {
        return this.id;
    }
    
    public void setId(CursoId id) {
        this.id = id;
    }
    public Docente getDocenteByImparteClases() {
        return this.docenteByImparteClases;
    }
    
    public void setDocenteByImparteClases(Docente docenteByImparteClases) {
        this.docenteByImparteClases = docenteByImparteClases;
    }
    public Docente getDocenteByDirige() {
        return this.docenteByDirige;
    }
    
    public void setDocenteByDirige(Docente docenteByDirige) {
        this.docenteByDirige = docenteByDirige;
    }
    public InstitucionesEdu getInstitucionesEdu() {
        return this.institucionesEdu;
    }
    
    public void setInstitucionesEdu(InstitucionesEdu institucionesEdu) {
        this.institucionesEdu = institucionesEdu;
    }
    public int getCurGrado() {
        return this.curGrado;
    }
    
    public void setCurGrado(int curGrado) {
        this.curGrado = curGrado;
    }
    public Set getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Set asignaturas) {
        this.asignaturas = asignaturas;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


