package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1



/**
 * CursoId generated by hbm2java
 */
public class CursoId  implements java.io.Serializable {


     private int curCod;
     private String docDirgrupo;

    public CursoId() {
    }

    public CursoId(int curCod, String docDirgrupo) {
       this.curCod = curCod;
       this.docDirgrupo = docDirgrupo;
    }
   
    public int getCurCod() {
        return this.curCod;
    }
    
    public void setCurCod(int curCod) {
        this.curCod = curCod;
    }
    public String getDocDirgrupo() {
        return this.docDirgrupo;
    }
    
    public void setDocDirgrupo(String docDirgrupo) {
        this.docDirgrupo = docDirgrupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CursoId) ) return false;
		 CursoId castOther = ( CursoId ) other; 
         
		 return (this.getCurCod()==castOther.getCurCod())
 && ( (this.getDocDirgrupo()==castOther.getDocDirgrupo()) || ( this.getDocDirgrupo()!=null && castOther.getDocDirgrupo()!=null && this.getDocDirgrupo().equals(castOther.getDocDirgrupo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCurCod();
         result = 37 * result + ( getDocDirgrupo() == null ? 0 : this.getDocDirgrupo().hashCode() );
         return result;
   }   


}


