package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer depId;
     private String depNombre;
     private Set municipios = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(String depNombre) {
        this.depNombre = depNombre;
    }
    public Departamento(String depNombre, Set municipios) {
       this.depNombre = depNombre;
       this.municipios = municipios;
    }
   
    public Integer getDepId() {
        return this.depId;
    }
    
    public void setDepId(Integer depId) {
        this.depId = depId;
    }
    public String getDepNombre() {
        return this.depNombre;
    }
    
    public void setDepNombre(String depNombre) {
        this.depNombre = depNombre;
    }
    public Set getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set municipios) {
        this.municipios = municipios;
    }




}


