package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private DocenteId id;
     private InstitucionesEdu institucionesEdu;
     private Usuarios usuarios;
     private String docNombre;
     private String docLugarExpdoc;
     private String docSexo;
     private String docTelefono;
     private String docDireccion;
     private String docEmail;
     private Date docFecnac;
     private String docLugarnac;
     private String docEstadocivil;
     private Set asignaturas = new HashSet(0);
     private Set asistencias = new HashSet(0);
     private Set notas = new HashSet(0);
     private Set cursosForImparteClases = new HashSet(0);
     private Set cursosForDirige = new HashSet(0);

    public Docente() {
    }

	
    public Docente(DocenteId id, InstitucionesEdu institucionesEdu, Usuarios usuarios, String docNombre, String docLugarExpdoc, String docSexo, String docTelefono, String docDireccion, String docEmail, Date docFecnac, String docLugarnac, String docEstadocivil) {
        this.id = id;
        this.institucionesEdu = institucionesEdu;
        this.usuarios = usuarios;
        this.docNombre = docNombre;
        this.docLugarExpdoc = docLugarExpdoc;
        this.docSexo = docSexo;
        this.docTelefono = docTelefono;
        this.docDireccion = docDireccion;
        this.docEmail = docEmail;
        this.docFecnac = docFecnac;
        this.docLugarnac = docLugarnac;
        this.docEstadocivil = docEstadocivil;
    }
    public Docente(DocenteId id, InstitucionesEdu institucionesEdu, Usuarios usuarios, String docNombre, String docLugarExpdoc, String docSexo, String docTelefono, String docDireccion, String docEmail, Date docFecnac, String docLugarnac, String docEstadocivil, Set asignaturas, Set asistencias, Set notas, Set cursosForImparteClases, Set cursosForDirige) {
       this.id = id;
       this.institucionesEdu = institucionesEdu;
       this.usuarios = usuarios;
       this.docNombre = docNombre;
       this.docLugarExpdoc = docLugarExpdoc;
       this.docSexo = docSexo;
       this.docTelefono = docTelefono;
       this.docDireccion = docDireccion;
       this.docEmail = docEmail;
       this.docFecnac = docFecnac;
       this.docLugarnac = docLugarnac;
       this.docEstadocivil = docEstadocivil;
       this.asignaturas = asignaturas;
       this.asistencias = asistencias;
       this.notas = notas;
       this.cursosForImparteClases = cursosForImparteClases;
       this.cursosForDirige = cursosForDirige;
    }
   
    public DocenteId getId() {
        return this.id;
    }
    
    public void setId(DocenteId id) {
        this.id = id;
    }
    public InstitucionesEdu getInstitucionesEdu() {
        return this.institucionesEdu;
    }
    
    public void setInstitucionesEdu(InstitucionesEdu institucionesEdu) {
        this.institucionesEdu = institucionesEdu;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getDocNombre() {
        return this.docNombre;
    }
    
    public void setDocNombre(String docNombre) {
        this.docNombre = docNombre;
    }
    public String getDocLugarExpdoc() {
        return this.docLugarExpdoc;
    }
    
    public void setDocLugarExpdoc(String docLugarExpdoc) {
        this.docLugarExpdoc = docLugarExpdoc;
    }
    public String getDocSexo() {
        return this.docSexo;
    }
    
    public void setDocSexo(String docSexo) {
        this.docSexo = docSexo;
    }
    public String getDocTelefono() {
        return this.docTelefono;
    }
    
    public void setDocTelefono(String docTelefono) {
        this.docTelefono = docTelefono;
    }
    public String getDocDireccion() {
        return this.docDireccion;
    }
    
    public void setDocDireccion(String docDireccion) {
        this.docDireccion = docDireccion;
    }
    public String getDocEmail() {
        return this.docEmail;
    }
    
    public void setDocEmail(String docEmail) {
        this.docEmail = docEmail;
    }
    public Date getDocFecnac() {
        return this.docFecnac;
    }
    
    public void setDocFecnac(Date docFecnac) {
        this.docFecnac = docFecnac;
    }
    public String getDocLugarnac() {
        return this.docLugarnac;
    }
    
    public void setDocLugarnac(String docLugarnac) {
        this.docLugarnac = docLugarnac;
    }
    public String getDocEstadocivil() {
        return this.docEstadocivil;
    }
    
    public void setDocEstadocivil(String docEstadocivil) {
        this.docEstadocivil = docEstadocivil;
    }
    public Set getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Set asignaturas) {
        this.asignaturas = asignaturas;
    }
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }
    public Set getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set notas) {
        this.notas = notas;
    }
    public Set getCursosForImparteClases() {
        return this.cursosForImparteClases;
    }
    
    public void setCursosForImparteClases(Set cursosForImparteClases) {
        this.cursosForImparteClases = cursosForImparteClases;
    }
    public Set getCursosForDirige() {
        return this.cursosForDirige;
    }
    
    public void setCursosForDirige(Set cursosForDirige) {
        this.cursosForDirige = cursosForDirige;
    }




}


