package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EstMadre generated by hbm2java
 */
public class EstMadre  implements java.io.Serializable {


     private String estMadreCod;
     private String estMadreNombre;
     private String estMadreLugarExpdoc;
     private String estMadreSexo;
     private String estMadreTelefono;
     private String estMadreDireccion;
     private String estMadreEmail;
     private Date estMadreFecnac;
     private String estMadreLugarnac;
     private int estMadreNivelsisben;
     private Set estudiantes = new HashSet(0);

    public EstMadre() {
    }

	
    public EstMadre(String estMadreCod, String estMadreNombre, String estMadreLugarExpdoc, String estMadreSexo, String estMadreTelefono, String estMadreDireccion, String estMadreEmail, Date estMadreFecnac, String estMadreLugarnac, int estMadreNivelsisben) {
        this.estMadreCod = estMadreCod;
        this.estMadreNombre = estMadreNombre;
        this.estMadreLugarExpdoc = estMadreLugarExpdoc;
        this.estMadreSexo = estMadreSexo;
        this.estMadreTelefono = estMadreTelefono;
        this.estMadreDireccion = estMadreDireccion;
        this.estMadreEmail = estMadreEmail;
        this.estMadreFecnac = estMadreFecnac;
        this.estMadreLugarnac = estMadreLugarnac;
        this.estMadreNivelsisben = estMadreNivelsisben;
    }
    public EstMadre(String estMadreCod, String estMadreNombre, String estMadreLugarExpdoc, String estMadreSexo, String estMadreTelefono, String estMadreDireccion, String estMadreEmail, Date estMadreFecnac, String estMadreLugarnac, int estMadreNivelsisben, Set estudiantes) {
       this.estMadreCod = estMadreCod;
       this.estMadreNombre = estMadreNombre;
       this.estMadreLugarExpdoc = estMadreLugarExpdoc;
       this.estMadreSexo = estMadreSexo;
       this.estMadreTelefono = estMadreTelefono;
       this.estMadreDireccion = estMadreDireccion;
       this.estMadreEmail = estMadreEmail;
       this.estMadreFecnac = estMadreFecnac;
       this.estMadreLugarnac = estMadreLugarnac;
       this.estMadreNivelsisben = estMadreNivelsisben;
       this.estudiantes = estudiantes;
    }
   
    public String getEstMadreCod() {
        return this.estMadreCod;
    }
    
    public void setEstMadreCod(String estMadreCod) {
        this.estMadreCod = estMadreCod;
    }
    public String getEstMadreNombre() {
        return this.estMadreNombre;
    }
    
    public void setEstMadreNombre(String estMadreNombre) {
        this.estMadreNombre = estMadreNombre;
    }
    public String getEstMadreLugarExpdoc() {
        return this.estMadreLugarExpdoc;
    }
    
    public void setEstMadreLugarExpdoc(String estMadreLugarExpdoc) {
        this.estMadreLugarExpdoc = estMadreLugarExpdoc;
    }
    public String getEstMadreSexo() {
        return this.estMadreSexo;
    }
    
    public void setEstMadreSexo(String estMadreSexo) {
        this.estMadreSexo = estMadreSexo;
    }
    public String getEstMadreTelefono() {
        return this.estMadreTelefono;
    }
    
    public void setEstMadreTelefono(String estMadreTelefono) {
        this.estMadreTelefono = estMadreTelefono;
    }
    public String getEstMadreDireccion() {
        return this.estMadreDireccion;
    }
    
    public void setEstMadreDireccion(String estMadreDireccion) {
        this.estMadreDireccion = estMadreDireccion;
    }
    public String getEstMadreEmail() {
        return this.estMadreEmail;
    }
    
    public void setEstMadreEmail(String estMadreEmail) {
        this.estMadreEmail = estMadreEmail;
    }
    public Date getEstMadreFecnac() {
        return this.estMadreFecnac;
    }
    
    public void setEstMadreFecnac(Date estMadreFecnac) {
        this.estMadreFecnac = estMadreFecnac;
    }
    public String getEstMadreLugarnac() {
        return this.estMadreLugarnac;
    }
    
    public void setEstMadreLugarnac(String estMadreLugarnac) {
        this.estMadreLugarnac = estMadreLugarnac;
    }
    public int getEstMadreNivelsisben() {
        return this.estMadreNivelsisben;
    }
    
    public void setEstMadreNivelsisben(int estMadreNivelsisben) {
        this.estMadreNivelsisben = estMadreNivelsisben;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


