package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EstPadre generated by hbm2java
 */
public class EstPadre  implements java.io.Serializable {


     private String estPadreCod;
     private String estPadreNombre;
     private String estPadreLugarExpdoc;
     private String estPadreSexo;
     private String estPadreTelefono;
     private String estPadreDireccion;
     private String estPadreEmail;
     private Date estPadreFecnac;
     private String estPadreLugarnac;
     private int estPadreNivelsisben;
     private Set estudiantes = new HashSet(0);

    public EstPadre() {
    }

	
    public EstPadre(String estPadreCod, String estPadreNombre, String estPadreLugarExpdoc, String estPadreSexo, String estPadreTelefono, String estPadreDireccion, String estPadreEmail, Date estPadreFecnac, String estPadreLugarnac, int estPadreNivelsisben) {
        this.estPadreCod = estPadreCod;
        this.estPadreNombre = estPadreNombre;
        this.estPadreLugarExpdoc = estPadreLugarExpdoc;
        this.estPadreSexo = estPadreSexo;
        this.estPadreTelefono = estPadreTelefono;
        this.estPadreDireccion = estPadreDireccion;
        this.estPadreEmail = estPadreEmail;
        this.estPadreFecnac = estPadreFecnac;
        this.estPadreLugarnac = estPadreLugarnac;
        this.estPadreNivelsisben = estPadreNivelsisben;
    }
    public EstPadre(String estPadreCod, String estPadreNombre, String estPadreLugarExpdoc, String estPadreSexo, String estPadreTelefono, String estPadreDireccion, String estPadreEmail, Date estPadreFecnac, String estPadreLugarnac, int estPadreNivelsisben, Set estudiantes) {
       this.estPadreCod = estPadreCod;
       this.estPadreNombre = estPadreNombre;
       this.estPadreLugarExpdoc = estPadreLugarExpdoc;
       this.estPadreSexo = estPadreSexo;
       this.estPadreTelefono = estPadreTelefono;
       this.estPadreDireccion = estPadreDireccion;
       this.estPadreEmail = estPadreEmail;
       this.estPadreFecnac = estPadreFecnac;
       this.estPadreLugarnac = estPadreLugarnac;
       this.estPadreNivelsisben = estPadreNivelsisben;
       this.estudiantes = estudiantes;
    }
   
    public String getEstPadreCod() {
        return this.estPadreCod;
    }
    
    public void setEstPadreCod(String estPadreCod) {
        this.estPadreCod = estPadreCod;
    }
    public String getEstPadreNombre() {
        return this.estPadreNombre;
    }
    
    public void setEstPadreNombre(String estPadreNombre) {
        this.estPadreNombre = estPadreNombre;
    }
    public String getEstPadreLugarExpdoc() {
        return this.estPadreLugarExpdoc;
    }
    
    public void setEstPadreLugarExpdoc(String estPadreLugarExpdoc) {
        this.estPadreLugarExpdoc = estPadreLugarExpdoc;
    }
    public String getEstPadreSexo() {
        return this.estPadreSexo;
    }
    
    public void setEstPadreSexo(String estPadreSexo) {
        this.estPadreSexo = estPadreSexo;
    }
    public String getEstPadreTelefono() {
        return this.estPadreTelefono;
    }
    
    public void setEstPadreTelefono(String estPadreTelefono) {
        this.estPadreTelefono = estPadreTelefono;
    }
    public String getEstPadreDireccion() {
        return this.estPadreDireccion;
    }
    
    public void setEstPadreDireccion(String estPadreDireccion) {
        this.estPadreDireccion = estPadreDireccion;
    }
    public String getEstPadreEmail() {
        return this.estPadreEmail;
    }
    
    public void setEstPadreEmail(String estPadreEmail) {
        this.estPadreEmail = estPadreEmail;
    }
    public Date getEstPadreFecnac() {
        return this.estPadreFecnac;
    }
    
    public void setEstPadreFecnac(Date estPadreFecnac) {
        this.estPadreFecnac = estPadreFecnac;
    }
    public String getEstPadreLugarnac() {
        return this.estPadreLugarnac;
    }
    
    public void setEstPadreLugarnac(String estPadreLugarnac) {
        this.estPadreLugarnac = estPadreLugarnac;
    }
    public int getEstPadreNivelsisben() {
        return this.estPadreNivelsisben;
    }
    
    public void setEstPadreNivelsisben(int estPadreNivelsisben) {
        this.estPadreNivelsisben = estPadreNivelsisben;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


