package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1



/**
 * EstudianteId generated by hbm2java
 */
public class EstudianteId  implements java.io.Serializable {


     private String estCod;
     private int curCod;
     private int insDcodigo;
     private int munId;
     private int depId;
     private String docDirgrupo;
     private int secCodigo;

    public EstudianteId() {
    }

    public EstudianteId(String estCod, int curCod, int insDcodigo, int munId, int depId, String docDirgrupo, int secCodigo) {
       this.estCod = estCod;
       this.curCod = curCod;
       this.insDcodigo = insDcodigo;
       this.munId = munId;
       this.depId = depId;
       this.docDirgrupo = docDirgrupo;
       this.secCodigo = secCodigo;
    }
   
    public String getEstCod() {
        return this.estCod;
    }
    
    public void setEstCod(String estCod) {
        this.estCod = estCod;
    }
    public int getCurCod() {
        return this.curCod;
    }
    
    public void setCurCod(int curCod) {
        this.curCod = curCod;
    }
    public int getInsDcodigo() {
        return this.insDcodigo;
    }
    
    public void setInsDcodigo(int insDcodigo) {
        this.insDcodigo = insDcodigo;
    }
    public int getMunId() {
        return this.munId;
    }
    
    public void setMunId(int munId) {
        this.munId = munId;
    }
    public int getDepId() {
        return this.depId;
    }
    
    public void setDepId(int depId) {
        this.depId = depId;
    }
    public String getDocDirgrupo() {
        return this.docDirgrupo;
    }
    
    public void setDocDirgrupo(String docDirgrupo) {
        this.docDirgrupo = docDirgrupo;
    }
    public int getSecCodigo() {
        return this.secCodigo;
    }
    
    public void setSecCodigo(int secCodigo) {
        this.secCodigo = secCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstudianteId) ) return false;
		 EstudianteId castOther = ( EstudianteId ) other; 
         
		 return ( (this.getEstCod()==castOther.getEstCod()) || ( this.getEstCod()!=null && castOther.getEstCod()!=null && this.getEstCod().equals(castOther.getEstCod()) ) )
 && (this.getCurCod()==castOther.getCurCod())
 && (this.getInsDcodigo()==castOther.getInsDcodigo())
 && (this.getMunId()==castOther.getMunId())
 && (this.getDepId()==castOther.getDepId())
 && ( (this.getDocDirgrupo()==castOther.getDocDirgrupo()) || ( this.getDocDirgrupo()!=null && castOther.getDocDirgrupo()!=null && this.getDocDirgrupo().equals(castOther.getDocDirgrupo()) ) )
 && (this.getSecCodigo()==castOther.getSecCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEstCod() == null ? 0 : this.getEstCod().hashCode() );
         result = 37 * result + this.getCurCod();
         result = 37 * result + this.getInsDcodigo();
         result = 37 * result + this.getMunId();
         result = 37 * result + this.getDepId();
         result = 37 * result + ( getDocDirgrupo() == null ? 0 : this.getDocDirgrupo().hashCode() );
         result = 37 * result + this.getSecCodigo();
         return result;
   }   


}


