package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private EstudianteId id;
     private Curso curso;
     private EstMadre estMadre;
     private EstPadre estPadre;
     private InstitucionesEdu institucionesEdu;
     private Usuarios usuarios;
     private String estado;
     private String estNombre;
     private String estLugarExpdoc;
     private String estSexo;
     private String estTelefono;
     private String estDireccion;
     private String estEmail;
     private Date estFecnac;
     private String estLugarnac;
     private String estEstadocivil;
     private String estSisben;
     private String estDesplazado;
     private int estEstratosoc;
     private Set notas = new HashSet(0);
     private Set asistencias = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(EstudianteId id, Curso curso, InstitucionesEdu institucionesEdu, Usuarios usuarios, String estNombre, String estLugarExpdoc, String estSexo, String estTelefono, String estDireccion, String estEmail, Date estFecnac, String estLugarnac, String estEstadocivil, String estSisben, String estDesplazado, int estEstratosoc) {
        this.id = id;
        this.curso = curso;
        this.institucionesEdu = institucionesEdu;
        this.usuarios = usuarios;
        this.estNombre = estNombre;
        this.estLugarExpdoc = estLugarExpdoc;
        this.estSexo = estSexo;
        this.estTelefono = estTelefono;
        this.estDireccion = estDireccion;
        this.estEmail = estEmail;
        this.estFecnac = estFecnac;
        this.estLugarnac = estLugarnac;
        this.estEstadocivil = estEstadocivil;
        this.estSisben = estSisben;
        this.estDesplazado = estDesplazado;
        this.estEstratosoc = estEstratosoc;
    }
    public Estudiante(EstudianteId id, Curso curso, EstMadre estMadre, EstPadre estPadre, InstitucionesEdu institucionesEdu, Usuarios usuarios, String estado, String estNombre, String estLugarExpdoc, String estSexo, String estTelefono, String estDireccion, String estEmail, Date estFecnac, String estLugarnac, String estEstadocivil, String estSisben, String estDesplazado, int estEstratosoc, Set notas, Set asistencias) {
       this.id = id;
       this.curso = curso;
       this.estMadre = estMadre;
       this.estPadre = estPadre;
       this.institucionesEdu = institucionesEdu;
       this.usuarios = usuarios;
       this.estado = estado;
       this.estNombre = estNombre;
       this.estLugarExpdoc = estLugarExpdoc;
       this.estSexo = estSexo;
       this.estTelefono = estTelefono;
       this.estDireccion = estDireccion;
       this.estEmail = estEmail;
       this.estFecnac = estFecnac;
       this.estLugarnac = estLugarnac;
       this.estEstadocivil = estEstadocivil;
       this.estSisben = estSisben;
       this.estDesplazado = estDesplazado;
       this.estEstratosoc = estEstratosoc;
       this.notas = notas;
       this.asistencias = asistencias;
    }
   
    public EstudianteId getId() {
        return this.id;
    }
    
    public void setId(EstudianteId id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public EstMadre getEstMadre() {
        return this.estMadre;
    }
    
    public void setEstMadre(EstMadre estMadre) {
        this.estMadre = estMadre;
    }
    public EstPadre getEstPadre() {
        return this.estPadre;
    }
    
    public void setEstPadre(EstPadre estPadre) {
        this.estPadre = estPadre;
    }
    public InstitucionesEdu getInstitucionesEdu() {
        return this.institucionesEdu;
    }
    
    public void setInstitucionesEdu(InstitucionesEdu institucionesEdu) {
        this.institucionesEdu = institucionesEdu;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getEstNombre() {
        return this.estNombre;
    }
    
    public void setEstNombre(String estNombre) {
        this.estNombre = estNombre;
    }
    public String getEstLugarExpdoc() {
        return this.estLugarExpdoc;
    }
    
    public void setEstLugarExpdoc(String estLugarExpdoc) {
        this.estLugarExpdoc = estLugarExpdoc;
    }
    public String getEstSexo() {
        return this.estSexo;
    }
    
    public void setEstSexo(String estSexo) {
        this.estSexo = estSexo;
    }
    public String getEstTelefono() {
        return this.estTelefono;
    }
    
    public void setEstTelefono(String estTelefono) {
        this.estTelefono = estTelefono;
    }
    public String getEstDireccion() {
        return this.estDireccion;
    }
    
    public void setEstDireccion(String estDireccion) {
        this.estDireccion = estDireccion;
    }
    public String getEstEmail() {
        return this.estEmail;
    }
    
    public void setEstEmail(String estEmail) {
        this.estEmail = estEmail;
    }
    public Date getEstFecnac() {
        return this.estFecnac;
    }
    
    public void setEstFecnac(Date estFecnac) {
        this.estFecnac = estFecnac;
    }
    public String getEstLugarnac() {
        return this.estLugarnac;
    }
    
    public void setEstLugarnac(String estLugarnac) {
        this.estLugarnac = estLugarnac;
    }
    public String getEstEstadocivil() {
        return this.estEstadocivil;
    }
    
    public void setEstEstadocivil(String estEstadocivil) {
        this.estEstadocivil = estEstadocivil;
    }
    public String getEstSisben() {
        return this.estSisben;
    }
    
    public void setEstSisben(String estSisben) {
        this.estSisben = estSisben;
    }
    public String getEstDesplazado() {
        return this.estDesplazado;
    }
    
    public void setEstDesplazado(String estDesplazado) {
        this.estDesplazado = estDesplazado;
    }
    public int getEstEstratosoc() {
        return this.estEstratosoc;
    }
    
    public void setEstEstratosoc(int estEstratosoc) {
        this.estEstratosoc = estEstratosoc;
    }
    public Set getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set notas) {
        this.notas = notas;
    }
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }




}


