package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1



/**
 * Indicadores generated by hbm2java
 */
public class Indicadores  implements java.io.Serializable {


     private IndicadoresId id;
     private Asignatura asignatura;
     private String indNombre;
     private int indPeriodo;

    public Indicadores() {
    }

    public Indicadores(IndicadoresId id, Asignatura asignatura, String indNombre, int indPeriodo) {
       this.id = id;
       this.asignatura = asignatura;
       this.indNombre = indNombre;
       this.indPeriodo = indPeriodo;
    }
   
    public IndicadoresId getId() {
        return this.id;
    }
    
    public void setId(IndicadoresId id) {
        this.id = id;
    }
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }
    public String getIndNombre() {
        return this.indNombre;
    }
    
    public void setIndNombre(String indNombre) {
        this.indNombre = indNombre;
    }
    public int getIndPeriodo() {
        return this.indPeriodo;
    }
    
    public void setIndPeriodo(int indPeriodo) {
        this.indPeriodo = indPeriodo;
    }




}


