package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1



/**
 * IndicadoresId generated by hbm2java
 */
public class IndicadoresId  implements java.io.Serializable {


     private int indCodigo;
     private int asiCod;
     private String docCod;
     private int insDcodigo;
     private int munId;
     private int depId;
     private int secCodigo;

    public IndicadoresId() {
    }

    public IndicadoresId(int indCodigo, int asiCod, String docCod, int insDcodigo, int munId, int depId, int secCodigo) {
       this.indCodigo = indCodigo;
       this.asiCod = asiCod;
       this.docCod = docCod;
       this.insDcodigo = insDcodigo;
       this.munId = munId;
       this.depId = depId;
       this.secCodigo = secCodigo;
    }
   
    public int getIndCodigo() {
        return this.indCodigo;
    }
    
    public void setIndCodigo(int indCodigo) {
        this.indCodigo = indCodigo;
    }
    public int getAsiCod() {
        return this.asiCod;
    }
    
    public void setAsiCod(int asiCod) {
        this.asiCod = asiCod;
    }
    public String getDocCod() {
        return this.docCod;
    }
    
    public void setDocCod(String docCod) {
        this.docCod = docCod;
    }
    public int getInsDcodigo() {
        return this.insDcodigo;
    }
    
    public void setInsDcodigo(int insDcodigo) {
        this.insDcodigo = insDcodigo;
    }
    public int getMunId() {
        return this.munId;
    }
    
    public void setMunId(int munId) {
        this.munId = munId;
    }
    public int getDepId() {
        return this.depId;
    }
    
    public void setDepId(int depId) {
        this.depId = depId;
    }
    public int getSecCodigo() {
        return this.secCodigo;
    }
    
    public void setSecCodigo(int secCodigo) {
        this.secCodigo = secCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IndicadoresId) ) return false;
		 IndicadoresId castOther = ( IndicadoresId ) other; 
         
		 return (this.getIndCodigo()==castOther.getIndCodigo())
 && (this.getAsiCod()==castOther.getAsiCod())
 && ( (this.getDocCod()==castOther.getDocCod()) || ( this.getDocCod()!=null && castOther.getDocCod()!=null && this.getDocCod().equals(castOther.getDocCod()) ) )
 && (this.getInsDcodigo()==castOther.getInsDcodigo())
 && (this.getMunId()==castOther.getMunId())
 && (this.getDepId()==castOther.getDepId())
 && (this.getSecCodigo()==castOther.getSecCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIndCodigo();
         result = 37 * result + this.getAsiCod();
         result = 37 * result + ( getDocCod() == null ? 0 : this.getDocCod().hashCode() );
         result = 37 * result + this.getInsDcodigo();
         result = 37 * result + this.getMunId();
         result = 37 * result + this.getDepId();
         result = 37 * result + this.getSecCodigo();
         return result;
   }   


}


