package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InstitucionesEdu generated by hbm2java
 */
public class InstitucionesEdu  implements java.io.Serializable {


     private InstitucionesEduId id;
     private Municipio municipio;
     private SecretariaEduc secretariaEduc;
     private String insDireccion;
     private String insNombre;
     private String insEmail;
     private String insTelefono;
     private Set administrativos = new HashSet(0);
     private Set cursos = new HashSet(0);
     private Set docentes = new HashSet(0);
     private Set estudiantes = new HashSet(0);

    public InstitucionesEdu() {
    }

	
    public InstitucionesEdu(InstitucionesEduId id, Municipio municipio, SecretariaEduc secretariaEduc, String insDireccion, String insNombre, String insEmail, String insTelefono) {
        this.id = id;
        this.municipio = municipio;
        this.secretariaEduc = secretariaEduc;
        this.insDireccion = insDireccion;
        this.insNombre = insNombre;
        this.insEmail = insEmail;
        this.insTelefono = insTelefono;
    }
    public InstitucionesEdu(InstitucionesEduId id, Municipio municipio, SecretariaEduc secretariaEduc, String insDireccion, String insNombre, String insEmail, String insTelefono, Set administrativos, Set cursos, Set docentes, Set estudiantes) {
       this.id = id;
       this.municipio = municipio;
       this.secretariaEduc = secretariaEduc;
       this.insDireccion = insDireccion;
       this.insNombre = insNombre;
       this.insEmail = insEmail;
       this.insTelefono = insTelefono;
       this.administrativos = administrativos;
       this.cursos = cursos;
       this.docentes = docentes;
       this.estudiantes = estudiantes;
    }
   
    public InstitucionesEduId getId() {
        return this.id;
    }
    
    public void setId(InstitucionesEduId id) {
        this.id = id;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public SecretariaEduc getSecretariaEduc() {
        return this.secretariaEduc;
    }
    
    public void setSecretariaEduc(SecretariaEduc secretariaEduc) {
        this.secretariaEduc = secretariaEduc;
    }
    public String getInsDireccion() {
        return this.insDireccion;
    }
    
    public void setInsDireccion(String insDireccion) {
        this.insDireccion = insDireccion;
    }
    public String getInsNombre() {
        return this.insNombre;
    }
    
    public void setInsNombre(String insNombre) {
        this.insNombre = insNombre;
    }
    public String getInsEmail() {
        return this.insEmail;
    }
    
    public void setInsEmail(String insEmail) {
        this.insEmail = insEmail;
    }
    public String getInsTelefono() {
        return this.insTelefono;
    }
    
    public void setInsTelefono(String insTelefono) {
        this.insTelefono = insTelefono;
    }
    public Set getAdministrativos() {
        return this.administrativos;
    }
    
    public void setAdministrativos(Set administrativos) {
        this.administrativos = administrativos;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }
    public Set getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set docentes) {
        this.docentes = docentes;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


