package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private MunicipioId id;
     private Departamento departamento;
     private String munNombre;
     private Set institucionesEdus = new HashSet(0);
     private Set secretariaEducs = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(MunicipioId id, Departamento departamento, String munNombre) {
        this.id = id;
        this.departamento = departamento;
        this.munNombre = munNombre;
    }
    public Municipio(MunicipioId id, Departamento departamento, String munNombre, Set institucionesEdus, Set secretariaEducs) {
       this.id = id;
       this.departamento = departamento;
       this.munNombre = munNombre;
       this.institucionesEdus = institucionesEdus;
       this.secretariaEducs = secretariaEducs;
    }
   
    public MunicipioId getId() {
        return this.id;
    }
    
    public void setId(MunicipioId id) {
        this.id = id;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getMunNombre() {
        return this.munNombre;
    }
    
    public void setMunNombre(String munNombre) {
        this.munNombre = munNombre;
    }
    public Set getInstitucionesEdus() {
        return this.institucionesEdus;
    }
    
    public void setInstitucionesEdus(Set institucionesEdus) {
        this.institucionesEdus = institucionesEdus;
    }
    public Set getSecretariaEducs() {
        return this.secretariaEducs;
    }
    
    public void setSecretariaEducs(Set secretariaEducs) {
        this.secretariaEducs = secretariaEducs;
    }




}


