package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1



/**
 * MunicipioId generated by hbm2java
 */
public class MunicipioId  implements java.io.Serializable {


     private int munId;
     private int depId;

    public MunicipioId() {
    }

    public MunicipioId(int munId, int depId) {
       this.munId = munId;
       this.depId = depId;
    }
   
    public int getMunId() {
        return this.munId;
    }
    
    public void setMunId(int munId) {
        this.munId = munId;
    }
    public int getDepId() {
        return this.depId;
    }
    
    public void setDepId(int depId) {
        this.depId = depId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MunicipioId) ) return false;
		 MunicipioId castOther = ( MunicipioId ) other; 
         
		 return (this.getMunId()==castOther.getMunId())
 && (this.getDepId()==castOther.getDepId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMunId();
         result = 37 * result + this.getDepId();
         return result;
   }   


}


