package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1



/**
 * NotaId generated by hbm2java
 */
public class NotaId  implements java.io.Serializable {


     private int asiCod;
     private String docCod;
     private int insDcodigo;
     private int munId;
     private int depId;
     private int secCodigo;
     private String estCod;
     private int curCod;
     private String docDirgrupo;

    public NotaId() {
    }

    public NotaId(int asiCod, String docCod, int insDcodigo, int munId, int depId, int secCodigo, String estCod, int curCod, String docDirgrupo) {
       this.asiCod = asiCod;
       this.docCod = docCod;
       this.insDcodigo = insDcodigo;
       this.munId = munId;
       this.depId = depId;
       this.secCodigo = secCodigo;
       this.estCod = estCod;
       this.curCod = curCod;
       this.docDirgrupo = docDirgrupo;
    }
   
    public int getAsiCod() {
        return this.asiCod;
    }
    
    public void setAsiCod(int asiCod) {
        this.asiCod = asiCod;
    }
    public String getDocCod() {
        return this.docCod;
    }
    
    public void setDocCod(String docCod) {
        this.docCod = docCod;
    }
    public int getInsDcodigo() {
        return this.insDcodigo;
    }
    
    public void setInsDcodigo(int insDcodigo) {
        this.insDcodigo = insDcodigo;
    }
    public int getMunId() {
        return this.munId;
    }
    
    public void setMunId(int munId) {
        this.munId = munId;
    }
    public int getDepId() {
        return this.depId;
    }
    
    public void setDepId(int depId) {
        this.depId = depId;
    }
    public int getSecCodigo() {
        return this.secCodigo;
    }
    
    public void setSecCodigo(int secCodigo) {
        this.secCodigo = secCodigo;
    }
    public String getEstCod() {
        return this.estCod;
    }
    
    public void setEstCod(String estCod) {
        this.estCod = estCod;
    }
    public int getCurCod() {
        return this.curCod;
    }
    
    public void setCurCod(int curCod) {
        this.curCod = curCod;
    }
    public String getDocDirgrupo() {
        return this.docDirgrupo;
    }
    
    public void setDocDirgrupo(String docDirgrupo) {
        this.docDirgrupo = docDirgrupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotaId) ) return false;
		 NotaId castOther = ( NotaId ) other; 
         
		 return (this.getAsiCod()==castOther.getAsiCod())
 && ( (this.getDocCod()==castOther.getDocCod()) || ( this.getDocCod()!=null && castOther.getDocCod()!=null && this.getDocCod().equals(castOther.getDocCod()) ) )
 && (this.getInsDcodigo()==castOther.getInsDcodigo())
 && (this.getMunId()==castOther.getMunId())
 && (this.getDepId()==castOther.getDepId())
 && (this.getSecCodigo()==castOther.getSecCodigo())
 && ( (this.getEstCod()==castOther.getEstCod()) || ( this.getEstCod()!=null && castOther.getEstCod()!=null && this.getEstCod().equals(castOther.getEstCod()) ) )
 && (this.getCurCod()==castOther.getCurCod())
 && ( (this.getDocDirgrupo()==castOther.getDocDirgrupo()) || ( this.getDocDirgrupo()!=null && castOther.getDocDirgrupo()!=null && this.getDocDirgrupo().equals(castOther.getDocDirgrupo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAsiCod();
         result = 37 * result + ( getDocCod() == null ? 0 : this.getDocCod().hashCode() );
         result = 37 * result + this.getInsDcodigo();
         result = 37 * result + this.getMunId();
         result = 37 * result + this.getDepId();
         result = 37 * result + this.getSecCodigo();
         result = 37 * result + ( getEstCod() == null ? 0 : this.getEstCod().hashCode() );
         result = 37 * result + this.getCurCod();
         result = 37 * result + ( getDocDirgrupo() == null ? 0 : this.getDocDirgrupo().hashCode() );
         return result;
   }   


}


