package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1



/**
 * Nota generated by hbm2java
 */
public class Nota  implements java.io.Serializable {


     private NotaId id;
     private Asignatura asignatura;
     private Docente docente;
     private Estudiante estudiante;
     private Float nota1;
     private Float nota2;
     private Integer nota3;
     private Integer notaDef;
     private Integer notaPeriodo;

    public Nota() {
    }

	
    public Nota(NotaId id, Asignatura asignatura, Docente docente, Estudiante estudiante) {
        this.id = id;
        this.asignatura = asignatura;
        this.docente = docente;
        this.estudiante = estudiante;
    }
    public Nota(NotaId id, Asignatura asignatura, Docente docente, Estudiante estudiante, Float nota1, Float nota2, Integer nota3, Integer notaDef, Integer notaPeriodo) {
       this.id = id;
       this.asignatura = asignatura;
       this.docente = docente;
       this.estudiante = estudiante;
       this.nota1 = nota1;
       this.nota2 = nota2;
       this.nota3 = nota3;
       this.notaDef = notaDef;
       this.notaPeriodo = notaPeriodo;
    }
   
    public NotaId getId() {
        return this.id;
    }
    
    public void setId(NotaId id) {
        this.id = id;
    }
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Float getNota1() {
        return this.nota1;
    }
    
    public void setNota1(Float nota1) {
        this.nota1 = nota1;
    }
    public Float getNota2() {
        return this.nota2;
    }
    
    public void setNota2(Float nota2) {
        this.nota2 = nota2;
    }
    public Integer getNota3() {
        return this.nota3;
    }
    
    public void setNota3(Integer nota3) {
        this.nota3 = nota3;
    }
    public Integer getNotaDef() {
        return this.notaDef;
    }
    
    public void setNotaDef(Integer notaDef) {
        this.notaDef = notaDef;
    }
    public Integer getNotaPeriodo() {
        return this.notaPeriodo;
    }
    
    public void setNotaPeriodo(Integer notaPeriodo) {
        this.notaPeriodo = notaPeriodo;
    }




}


