package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1



/**
 * SecretariaEducId generated by hbm2java
 */
public class SecretariaEducId  implements java.io.Serializable {


     private int secCodigo;
     private int munId;
     private int depId;

    public SecretariaEducId() {
    }

    public SecretariaEducId(int secCodigo, int munId, int depId) {
       this.secCodigo = secCodigo;
       this.munId = munId;
       this.depId = depId;
    }
   
    public int getSecCodigo() {
        return this.secCodigo;
    }
    
    public void setSecCodigo(int secCodigo) {
        this.secCodigo = secCodigo;
    }
    public int getMunId() {
        return this.munId;
    }
    
    public void setMunId(int munId) {
        this.munId = munId;
    }
    public int getDepId() {
        return this.depId;
    }
    
    public void setDepId(int depId) {
        this.depId = depId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SecretariaEducId) ) return false;
		 SecretariaEducId castOther = ( SecretariaEducId ) other; 
         
		 return (this.getSecCodigo()==castOther.getSecCodigo())
 && (this.getMunId()==castOther.getMunId())
 && (this.getDepId()==castOther.getDepId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSecCodigo();
         result = 37 * result + this.getMunId();
         result = 37 * result + this.getDepId();
         return result;
   }   


}


