package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SecretariaEduc generated by hbm2java
 */
public class SecretariaEduc  implements java.io.Serializable {


     private SecretariaEducId id;
     private Municipio municipio;
     private String secDireccion;
     private String secNombreRep;
     private String secEmailRep;
     private String secTelefono;
     private Set institucionesEdus = new HashSet(0);

    public SecretariaEduc() {
    }

	
    public SecretariaEduc(SecretariaEducId id, Municipio municipio, String secDireccion, String secNombreRep, String secEmailRep, String secTelefono) {
        this.id = id;
        this.municipio = municipio;
        this.secDireccion = secDireccion;
        this.secNombreRep = secNombreRep;
        this.secEmailRep = secEmailRep;
        this.secTelefono = secTelefono;
    }
    public SecretariaEduc(SecretariaEducId id, Municipio municipio, String secDireccion, String secNombreRep, String secEmailRep, String secTelefono, Set institucionesEdus) {
       this.id = id;
       this.municipio = municipio;
       this.secDireccion = secDireccion;
       this.secNombreRep = secNombreRep;
       this.secEmailRep = secEmailRep;
       this.secTelefono = secTelefono;
       this.institucionesEdus = institucionesEdus;
    }
   
    public SecretariaEducId getId() {
        return this.id;
    }
    
    public void setId(SecretariaEducId id) {
        this.id = id;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getSecDireccion() {
        return this.secDireccion;
    }
    
    public void setSecDireccion(String secDireccion) {
        this.secDireccion = secDireccion;
    }
    public String getSecNombreRep() {
        return this.secNombreRep;
    }
    
    public void setSecNombreRep(String secNombreRep) {
        this.secNombreRep = secNombreRep;
    }
    public String getSecEmailRep() {
        return this.secEmailRep;
    }
    
    public void setSecEmailRep(String secEmailRep) {
        this.secEmailRep = secEmailRep;
    }
    public String getSecTelefono() {
        return this.secTelefono;
    }
    
    public void setSecTelefono(String secTelefono) {
        this.secTelefono = secTelefono;
    }
    public Set getInstitucionesEdus() {
        return this.institucionesEdus;
    }
    
    public void setInstitucionesEdus(Set institucionesEdus) {
        this.institucionesEdus = institucionesEdus;
    }




}


