package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private UserRoleId id;
     private Usuarios usuarios;
     private Date roleCreated;
     private Date roleUpdate;

    public UserRole() {
    }

	
    public UserRole(UserRoleId id, Usuarios usuarios) {
        this.id = id;
        this.usuarios = usuarios;
    }
    public UserRole(UserRoleId id, Usuarios usuarios, Date roleCreated, Date roleUpdate) {
       this.id = id;
       this.usuarios = usuarios;
       this.roleCreated = roleCreated;
       this.roleUpdate = roleUpdate;
    }
   
    public UserRoleId getId() {
        return this.id;
    }
    
    public void setId(UserRoleId id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getRoleCreated() {
        return this.roleCreated;
    }
    
    public void setRoleCreated(Date roleCreated) {
        this.roleCreated = roleCreated;
    }
    public Date getRoleUpdate() {
        return this.roleUpdate;
    }
    
    public void setRoleUpdate(Date roleUpdate) {
        this.roleUpdate = roleUpdate;
    }




}


