package pojos;
// Generated 25/09/2016 04:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String usrId;
     private String usrPassword;
     private String usrToken;
     private Date usrCreated;
     private Date usrUpdate;
     private Set userRoles = new HashSet(0);
     private Set estudiantes = new HashSet(0);
     private Set docentes = new HashSet(0);
     private Set administrativos = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String usrId, String usrPassword, String usrToken, Date usrCreated) {
        this.usrId = usrId;
        this.usrPassword = usrPassword;
        this.usrToken = usrToken;
        this.usrCreated = usrCreated;
    }
    public Usuarios(String usrId, String usrPassword, String usrToken, Date usrCreated, Date usrUpdate, Set userRoles, Set estudiantes, Set docentes, Set administrativos) {
       this.usrId = usrId;
       this.usrPassword = usrPassword;
       this.usrToken = usrToken;
       this.usrCreated = usrCreated;
       this.usrUpdate = usrUpdate;
       this.userRoles = userRoles;
       this.estudiantes = estudiantes;
       this.docentes = docentes;
       this.administrativos = administrativos;
    }
   
    public String getUsrId() {
        return this.usrId;
    }
    
    public void setUsrId(String usrId) {
        this.usrId = usrId;
    }
    public String getUsrPassword() {
        return this.usrPassword;
    }
    
    public void setUsrPassword(String usrPassword) {
        this.usrPassword = usrPassword;
    }
    public String getUsrToken() {
        return this.usrToken;
    }
    
    public void setUsrToken(String usrToken) {
        this.usrToken = usrToken;
    }
    public Date getUsrCreated() {
        return this.usrCreated;
    }
    
    public void setUsrCreated(Date usrCreated) {
        this.usrCreated = usrCreated;
    }
    public Date getUsrUpdate() {
        return this.usrUpdate;
    }
    
    public void setUsrUpdate(Date usrUpdate) {
        this.usrUpdate = usrUpdate;
    }
    public Set getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set userRoles) {
        this.userRoles = userRoles;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Set getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set docentes) {
        this.docentes = docentes;
    }
    public Set getAdministrativos() {
        return this.administrativos;
    }
    
    public void setAdministrativos(Set administrativos) {
        this.administrativos = administrativos;
    }




}


